name: analytics
description: Shared analytics mechanism for the Twilight platform.
publish_to: none
version: 0.1.0

resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
